name = "ecommerce2"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce2"
database_id = "1391bd30-4bf7-49fe-80a9-4c1d86b0c3a8"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
